burn_in: false
burn_step: 5
cal: 20
fx: 1.5
fy: 1.5
gpu_id: '3'
ksp_path: /home/ague/data/gluo/dataset/LI/LI, Dahui_T2S_1.npz
lamb: 13
model_folder: /home/gluo/logs/20230204-231435
model_name: ncsn_brain_100
n_steps_each: 30
nr_samples: 10
poisson: true
psnr: 1
sampling_rate: 0.2
workspace: /home/gluo/workspace/sampling_posterior/multi_coils_exp
disable_z: True