cal: 20
fx: 2
fy: 2
dropout: 0
lamb: 8
iterations: 100
workspace: /home/gluo/workspace/sampling_posterior/pixelcnn_plus
ksp_path: /home/ague/data/gluo/dataset/LI/LI, Dahui_T2S_1.npz
model_folder: /home/gluo/logs/20220525-110228
model_name: pixelcnn_500
gpu_id: '2'