model: 'PIXELCNN'
batch_size: 3
input_shape: [256, 256, 2]
nr_resnet: 3
nr_filters: 100
nr_logistic_mix: 10
data_chns: 'CPLX'
dropout_rate: 0.5
itg_interval: 255.0
rlt: 1
layer_norm: False
conditional: False

lr: 0.0001

max_keep: 100
max_epochs: 500
save_interval: 50
saved_name: pixelcnn
log_folder: /home/gluo/logs

train_data_path: /home/ague/data/gluo/dataset/brain_mat/train
test_data_path: /home/ague/data/gluo/dataset/brain_mat/test   # not needed
dataset_suffix: 'npz'
pattern: "hku_*.npz"
num_prepare: 10
print_loss: True

nr_gpu: 2
gpu_id: '1,2'