## model
model: "SDE"
batch_size: 10
input_shape: [256, 256, 2]
data_chns: 'CPLX'
lr: 0.0001
sigma_max: 1.
sigma_min: 0.001
N: 200
eps: 1.e-5
reduce_mean: False

seed: 1234
net: 'refine'
body: small
nr_filters: 64
nonlinearity: 'elu'
fourier_scale: 16
affine_x: False
attention: True
likelihood_weighting: True

max_keep: 100
max_epochs: 1000
save_interval: 50
saved_name: sde_brain
log_folder: /home/gluo/logs

train_data_path: /home/ague/data/gluo/dataset/brain_mat/train
test_data_path: /home/ague/data/gluo/dataset/brain_mat/test
dataset_suffix: 'npz'
pattern: "hku_*.npz"
num_prepare: 10
print_loss: True
parts: 
    - [{func: 'npz_loader', key: 'rss'}, {func: 'squeeze'}, {func: 'normalize_with_max'}, {func: 'slice_image', shape: [256, 256, 2]}]
    - [{func: 'randfloat', eps: 1.e-5, T: 1. }]
nr_gpu: 1
gpu_id: '3'
