burn_in: false
burn_t: 0.5
c_steps: 5
cal: 20
compute_residual: true
fx: 2
fy: 2
gpu_id: '3'
ksp_path: /home/ague/data/gluo/dataset/LI/LI, Dahui_T2S_1.npz
ext_iter: 200
ode: True
model_folder: /home/ague/archive/projects/2021/gluo/mcmc_recon/models/net2/20211007-232921
model_name: sde_brain_500
nr_samples: 1
poisson: true
s_stepsize: 25
sampling_rate: 0.2
st: 30
target_snr: 1
workspace: /home/gluo/workspace/sampling_posterior/map_end
disable_z: True
save_intermediate: True