# undersampling mask
poisson: true
fx: 2
fy: 2
cal: 20
sampling_rate: 0.2
ksp_path: /home/ague/data/gluo/dataset/LI/LI, Dahui_T2S_1.npz

nr_samples: 10
s_stepsize: 25
st: 10
target_snr: 1
disable_z: True
c_steps: 5
burn_in: false
burn_t: 0.7

gpu_id: '3'
workspace: /home/gluo/workspace/sampling_posterior/mcmc_pixelcnn

# 
model_folder: /home/ague/archive/projects/2021/gluo/mcmc_recon/models/net2/20211007-232921
model_name: sde_brain_500

# pixelcnn reg
use_pixelcnn: True
pixelcnn_config: /home/ague/archive/projects/2021/gluo/mcmc_recon/models/pixelcnn/20220525-110228/config.yaml
pixelcnn_path: /home/ague/archive/projects/2021/gluo/mcmc_recon/models/pixelcnn/20220525-110228/pixelcnn_500
dropout: 0.1
pixelcnn_lamb: 8
save_intermediate: True
