burn_in: false
burn_t: 0.5
c_steps: 5
cal: 20
compute_residual: true
ksp_path: /home/ague/data/gluo/dataset/LI/LI, Dahui_T2S_1.npz
model_folder: /home/ague/archive/projects/2021/gluo/mcmc_recon/models/net2/20211007-232921
model_name: sde_brain_500
nr_samples: 10
poisson: true
fx: 1.5
fy: 1.5
s_stepsize: 25
st: 30
target_snr: 1
workspace: /home/gluo/workspace/sampling_posterior/more_noise_scales
disable_z: True
gpu_id: '3'