burn_in: false
burn_t: 0.5
c_steps: 5
cal: 20
compute_residual: true
fx: 1.5
fy: 1.5
gpu_id: '3'
ksp_path: /home/gluo/workspace/sampling_posterior/transferability/t2_slice_26.cfl
model_folder: /home/ague/archive/projects/2021/gluo/mcmc_recon/models/net3/20211006-232740
model_name: sde_brain_500
nr_samples: 10
poisson: true
s_stepsize: 20
sampling_rate: 0.2
st: 30
target_snr: 1
workspace: /home/gluo/workspace/sampling_posterior/transferability_2
disable_z: True
save_intermediate: False