model: 'NCSN'
batch_size: 10
input_shape: [256, 256, 2]
data_chns: 'CPLX'
lr: 0.0001
begin_sigma: 0.3
end_sigma: 0.01
anneal_power: 2.
nr_levels: 20
affine_x: false
nonlinearity: 'elu'
nr_filters: 100

seed: 1234
max_keep: 100
max_epochs: 1000
save_interval: 50
saved_name: ncsn_brain
log_folder: /home/gluo/logs

train_data_path: /home/ague/data/gluo/dataset/brain_mat/train
test_data_path: /home/ague/data/gluo/dataset/brain_mat/test
pattern: "hku_*.npz"
num_prepare: 10
print_loss: True
parts: 
    - [{func: 'npz_loader', key: 'rss'}, {func: 'squeeze'}, {func: 'normalize_with_max'}, {func: 'slice_image', shape: [256, 256, 2]}]
    - [{func: 'randint', nr_levels: 20}]
nr_gpu: 3
gpu_id: '1,2,3'
