## DDPM
model: "SDE2"
batch_size: 10
input_shape: [256, 256, 2]
data_chns: 2

sigma_max: 20.
sigma_min: 0.1
N: 1000
eps: 1.e-5
reduce_mean: True
continuous: False

lr_warm_up_steps: 1000
lr_start: 0.0001
lr_min: 0.0001
lr_max: 0.0001
lr_max_decay_steps: 2000


seed: 1234
net: 'refine'
body: small
nr_filters: 64
nonlinearity: 'elu'
fourier_scale: 16
affine_x: False
attention: False

max_keep: 100
max_epochs: 3000
save_interval: 50
saved_name: ddpm_hku
log_folder: /home/gluo/workspace/nlinv_prior/logs
restore_path: /home/gluo/workspace/nlinv_prior/logs/20230501-102203/ddpm_hku_250

num_thread: 30
print_loss: True
train_list: /home/gluo/workspace/nlinv_prior/data/hku/hku_train
test_list: /home/gluo/workspace/nlinv_prior/data/hku/hku_test

nr_gpu: 3
gpu_id: '0,1,2'
