cal: 20
fx: 1.5
fy: 1.5
poisson: true
sampling_rate: 0.2
s_stepsize: 25
st: 30
c_steps: 5
nr_samples: 10
burn_in: false
burn_t: 0.5
disable_z: True
target_snr: 1

ksp_path: ./spreco/data/full_kspace.npz
model_folder: ./spreco/data/pre-trained
model_name: brain_model
gpu_id: '3'




