model: 'NCSN'
batch_size: 4
input_shape: [256, 256, 2]
data_chns: 'CPLX'
lr: 0.0001
begin_sigma: 0.3
end_sigma: 0.01
anneal_power: 2.
nr_levels: 10
affine_x: True
nonlinearity: 'elu'
nr_filters: 64

seed: 1234
max_keep: 100
max_epochs: 1000
save_interval: 50
saved_name: ncsn_brain
log_folder: xxxx

train_data_path: xxxx
test_data_path: xxxx
pattern: "hku_*.npz"
num_prepare: 10
print_loss: True
parts: 
    - [{func: 'npz_loader', key: 'rss'}, {func: 'squeeze'}, {func: 'normalize_with_max'}, {func: 'slice_image', shape: [256, 256, 2]}]
    - [{func: 'randint', nr_levels: 10}]
nr_gpu: 2
gpu_id: '1,2'
