model: 'NCSN'
batch_size: 2
input_shape: [256, 256, 2]
data_chns: 'CPLX'
lr: 0.0001
begin_sigma: 0.3
end_sigma: 0.01
anneal_power: 2.
nr_levels: 10
affine_x: True
nonlinearity: 'elu'
nr_filters: 64

seed: 1234
max_keep: 100
max_epochs: 1000
save_interval: 50
saved_name: ncsn_brain
log_folder: /content/logs
print_loss: True

train_data_path: /content/spreco/data/brain_mnist/train
test_data_path: /content/spreco/data/brain_mnist/test
pattern: "*.npz"
num_prepare: 10


nr_gpu: 1
gpu_id: '0'
